# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIHw0MbPaX_rr9fDubhBAbQ27vH8wKKq
"""

# Import libraries
import streamlit as st
import pandas as pd
from joblib import load

# Load the trained model
model = load('/content/trained_modelXG.joblib')

# App title
st.title("Car Price Prediction")

# User inputs
year = st.number_input("Year of Manufacture", min_value=1990, max_value=2024, step=1)
kms_driven = st.number_input("Kilometers Driven", min_value=0, step=500)
fuel_type = st.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG"])
seller_type = st.selectbox("Seller Type", ["Dealer", "Individual"])
transmission = st.selectbox("Transmission Type", ["Manual", "Automatic"])
owner = st.selectbox("Previous Owners", [0, 1, 2, 3])

# Preprocess user inputs
fuel_type_dict = {"Petrol": 0, "Diesel": 1, "CNG": 0}
seller_type_dict = {"Dealer": 0, "Individual": 1}
transmission_dict = {"Manual": 0, "Automatic": 1}

input_data = pd.DataFrame({
    'Year': [year],
    'Kms_Driven': [kms_driven],
    'Fuel_Type_Diesel': [fuel_type_dict[fuel_type]],
    'Fuel_Type_CNG': [fuel_type == "CNG"],
    'Seller_Type_Individual': [seller_type_dict[seller_type]],
    'Transmission_Manual': [transmission_dict[transmission]],
    'Owner': [owner]
})

# Predict price
if st.button("Predict Price"):
    prediction = model.predict(input_data)[0]
    st.success(f"Estimated Selling Price: ₹{prediction:.2f}")
